sudo: required
language: java
matrix:
  include:
    - jdk: openjdk8
      env: WLP_VERSION=17.0.0.3
    - jdk: openjdk8
      env: WLP_VERSION=17.0.0.4
script:
  - export GRADLE_OPTS="-Dorg.gradle.daemon=true -Dorg.gradle.jvmargs='-XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m'"
  - travis_wait ./gradlew install check -Prunit=online -DwlpVersion=$WLP_VERSION --stacktrace --info --no-daemon
after_failure:
  - cat /home/travis/build/WASdev/ci.gradle/build/testBuilds/arquillian-tests/build/reports/verify-main-app-managed/index.html 
  - cat /home/travis/build/WASdev/ci.gradle/build/reports/tests/integrationTest/index.html
  - cat /home/travis/build/WASdev/ci.gradle/build/testBuilds/arquillian-tests/build/wlp/usr/servers/LibertyProjectServer/logs/messages.log
dist: trusty
